# .streamlit/config.toml

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
base = "light"
primaryColor = "#16a34a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"
